# QR Decomposition with Gram-Schmidt

This notebook shows decompositon of a matrix A to orthogonal matrix Q and upper triangular matrix R

References:

1. Stephen Boyd and Lieven Vandenberghe [Introduction to Applied Linear Algebra - Vectors, Matrices, and Least Squares](http://vmls-book.stanford.edu), Chapter 5.4 and 10.4.
2. James W. Demmel Applied Numerical Linear Algebra, Chapter 3.2.2

The implementation follows Algorithm 3.1 from [2], you can find Matlab implementation [here](http://it6-1605.narod.ru/#gramm_shmidt)

In [1]:
import numpy as np

In [2]:
A = np.array((-1, 1, -1, 1, -1, 3, -1, 3, 1, 3, 5, 7), dtype=float).reshape(3, 4).T
A

array([[-1., -1.,  1.],
       [ 1.,  3.,  3.],
       [-1., -1.,  5.],
       [ 1.,  3.,  7.]])

Allocate matrices Q and R

In [3]:
Q = np.zeros(A.shape)
R = np.zeros((A.shape[1], A.shape[1]))

Perform computations

In [4]:
for i in np.arange(A.shape[1]):
    Q[:,[i]] = A[:, [i]]

    # Substract component in q_j direction from a_i
    for j in np.arange(i):
        R[j, i] = Q[:, [j]].T.dot(Q[:, [i]])
        Q[:, [i]] = Q[:, [i]] - R[j, i] * Q[:, [j]]

    R[i, i] = np.sqrt(Q[:, [i]].T.dot(Q[:, [i]]))
    Q[:, [i]] = Q[:, [i]] / R[i, i]

In [5]:
# orthogonal matrix Q
Q

array([[-0.5,  0.5, -0.5],
       [ 0.5,  0.5, -0.5],
       [-0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5]])

In [6]:
# upper diagonal matrix R
R

array([[2., 4., 2.],
       [0., 2., 8.],
       [0., 0., 4.]])

Check the that $${A = QR}$$

In [7]:
np.allclose(A, Q.dot(R))

True

Check that Q is an orthogonal matrix $${Q^{T}Q = I}$$

In [8]:
np.allclose(Q.T.dot(Q), np.eye(Q.shape[1]))

True